mkdir -p /home/applepie/Data/psync/0
mkdir -p /home/applepie/Data/psync/1
mkdir -p /home/applepie/Data/psync/2
mkdir -p /home/applepie/Data/psync/3
mkdir -p /home/applepie/Data/psync/4
mkdir -p /home/applepie/Data/psync/5
mkdir -p /home/applepie/Data/psync/6
mkdir -p /home/applepie/Data/psync/7
mkdir -p /home/applepie/Data/psync/8
mkdir -p /home/applepie/Data/psync/9
mkdir -p /home/applepie/Data/psync/a
mkdir -p /home/applepie/Data/psync/b
mkdir -p /home/applepie/Data/psync/c
mkdir -p /home/applepie/Data/psync/d
mkdir -p /home/applepie/Data/psync/e
mkdir -p /home/applepie/Data/psync/f
mkdir -p /home/applepie/Data/psync/import_from_disk
mkdir -p /home/applepie/Data/psync/import_from_phone
