mkdir -p ./0
mkdir -p ./1
mkdir -p ./2
mkdir -p ./3
mkdir -p ./4
mkdir -p ./5
mkdir -p ./6
mkdir -p ./7
mkdir -p ./8
mkdir -p ./9
mkdir -p ./a
mkdir -p ./b
mkdir -p ./c
mkdir -p ./d
mkdir -p ./e
mkdir -p ./f
mkdir -p ./import_root/import_from_disk
mkdir -p ./import_root/import_from_phone

mkdir -p ./scripts/
mkdir -p ./backups/

mkdir -p ./convert/0
mkdir -p ./convert/1
mkdir -p ./convert/2
mkdir -p ./convert/3
mkdir -p ./convert/4
mkdir -p ./convert/5
mkdir -p ./convert/6
mkdir -p ./convert/7
mkdir -p ./convert/8
mkdir -p ./convert/9
mkdir -p ./convert/a
mkdir -p ./convert/b
mkdir -p ./convert/c
mkdir -p ./convert/d
mkdir -p ./convert/e
mkdir -p ./convert/f

mkdir -p ./face/0
mkdir -p ./face/1
mkdir -p ./face/2
mkdir -p ./face/3
mkdir -p ./face/4
mkdir -p ./face/5
mkdir -p ./face/6
mkdir -p ./face/7
mkdir -p ./face/8
mkdir -p ./face/9
mkdir -p ./face/a
mkdir -p ./face/b
mkdir -p ./face/c
mkdir -p ./face/d
mkdir -p ./face/e
mkdir -p ./face/f
