mkdir -p ./0
mkdir -p ./1
mkdir -p ./2
mkdir -p ./3
mkdir -p ./4
mkdir -p ./5
mkdir -p ./6
mkdir -p ./7
mkdir -p ./8
mkdir -p ./9
mkdir -p ./a
mkdir -p ./b
mkdir -p ./c
mkdir -p ./d
mkdir -p ./e
mkdir -p ./f
mkdir -p ./import_root/import_from_disk
mkdir -p ./import_root/import_from_phone

mkdir -p ./convert/0
mkdir -p ./convert/1
mkdir -p ./convert/2
mkdir -p ./convert/3
mkdir -p ./convert/4
mkdir -p ./convert/5
mkdir -p ./convert/6
mkdir -p ./convert/7
mkdir -p ./convert/8
mkdir -p ./convert/9
mkdir -p ./convert/a
mkdir -p ./convert/b
mkdir -p ./convert/c
mkdir -p ./convert/d
mkdir -p ./convert/e
mkdir -p ./convert/f
